{
 "title": "Dashboard Production",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU utilisé en moyenne par production(en %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((avg(node_memory_MemAvailable_bytes{namespace=\"production\"}) / avg(node_memory_MemTotal_bytes{namespace=\"production\"})) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mémoire libre utilisable par le namespace production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{namespace=\"production\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre total de pod dans le namespace production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=\"production\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre total de requêtes dans le namespace production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_requests_total{namespace=\"production\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}