apiVersion: v1
kind: PersistentVolume
metadata:
  name: csv-pv
  namespace: production
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/csv-files"  # Chemin sur le nœud Kubernetes (pour un stockage local)
