apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: production
spec:
  hard:
    cpu: "3"          
    memory: "6Gi"   
    pods: "15"        
    requests.cpu: "2"  
    requests.memory: "6Gi"
