apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-api
  template:
    metadata:
      labels:
        app: search-api
    spec:
      containers:
      - name: search-api
        image: legault291/search-api:latest
        ports:
        - containerPort: 5003
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: SEARCH_SERVICE_PORT
          value: "5003"
        - name: ADMIN_KEY
          value: "default_key"
        volumeMounts:
        - name: csv-storage
          mountPath: /data
      volumes:
      - name: csv-storage
        persistentVolumeClaim:
          claimName: csv-pvc
